spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testdb
        username: sa
        password: "{cipher}AQBgyLm3kHmLrEJAgzE8KJ6oEtpwMrBDI4ZU5cUIve3wDn2R46Svlnd7fPmq0HJ8gmk1H7ghdIpfmxtemSDifCUB2lZEZyLxdNw/qyp2AGiG+ZJCBU9LQcAxZJ3x4QrJsIdUz3QreHMr1sxCWm6oqAZ5Cu3sUuMkj08ToYM3h3Itd/FclIqfCHrA0dXxhBijJWxs7xzrrE18kKV+nakoV96G3XfQ9bh/sCkVN4Wg1YqEMyJJzknYurIIIt3ndZpBLZVD6/It+bYTZcXs1mm/kYvIbhcc9AwchTjRslpdtGnv+S71I6NIzog5iCFfE+VZrGCqUuwxc77gZzh4t/y+qx37c2CKglBZ9QYBO9pCVV2sUaCBDbxjdb27d7zrkuvkeuM="

token:
    expiration_time: 8640000001
    secret: user_token_native_application

gateway:
    ip: 192.168.31.218

order_service:
    url: http://ORDER-SERVICE/order-service/%s/orders
